#!/bin/sh
component="$1"
version="$2"

if [[ "$component" == "" ]]; then
  echo "missing component"
  exit 1
fi

if [[ "$version" == "" ]]; then
  echo "missing version"
  exit 1
fi

if [[ "$component" != "client" && "$component" != "server" ]]; then
  echo "unknown component $component"
  exit 1
fi

script_dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"
sh "$script_dir/test" "$component"

default_args=()
if [[ "$component" == "client" ]]; then
  default_args=("--build-arg" "SERVER_HOST=https://tlowerison.com")
fi

docker build . -t "tlowerison/tilings-$component:$version" -f "Dockerfile.$component" \
  ${default_args[@]} \
  ${@:3}
