FROM rust:1.52.1 AS build-rust

  WORKDIR /app/rust/server

  COPY \
    rust/server/Cargo.toml \
    rust/server/Cargo.lock \
    rust/server/rust-toolchain.toml \
    .

  RUN \
    mkdir -p src && \
    echo "fn main() {}" > src/main.rs && \
    cargo fetch

  COPY rust/server/ .

  RUN cargo build

FROM rust:1.52.1

  WORKDIR /app

  COPY --from=build-rust /app/rust/server/target/debug/server /app/server

  EXPOSE 8000
  CMD ["/app/server"]
