#!/bin/sh

component="$1"

if [[ "$component" == "" ]]; then
  echo "missing component"
  exit 1
fi

if [[ "$component" != "client" && "$component" != "server" ]]; then
  echo "unknown component $component"
  exit 1
fi

if [[ "$component" == "client" ]]; then

  mkdir -p www/pkg

  cd rust/client

  if [ -z "$(which wasm-pack)" ]
  then
  	cargo install wasm-pack
  fi

  export SERVER_HOST="http://localhost:8000"
  wasm-pack build --out-dir ../../www/pkg || exit

  cd ../../www
  yarn add ./pkg
  yarn
  yarn start

elif [[ "$component" == "server" ]]; then

  cd rust/server
  cargo build && ./cred local ../target/debug/server

fi
