#!/bin/sh
set -e

CONFIG=release
mkdir -p www/pkg

cd rust/client

if [ -z "$(which wasm-pack)" ]
then
	cargo install wasm-pack
fi

wasm-pack build --out-dir ../../www/pkg

cd ../../www
yarn add ./pkg
yarn
yarn start
