#!/bin/sh
mkdir -p www/pkg

cd rust/client

if [ -z "$(which wasm-pack)" ]
then
	cargo install wasm-pack
fi

export SERVER_HOST="http://localhost:8000"
wasm-pack build --out-dir ../../www/pkg || exit

cd ../../www
yarn add ./pkg
yarn
yarn start
