#!/bin/sh
component="$1"

if [[ "$component" == "" ]]; then
  echo "missing component"
  exit 1
fi

if [[ "$component" != "client" && "$component" != "server" ]]; then
  echo "unknown component $component"
  exit 1
fi

base=""
packages=()
script_dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)"

if [[ "$component" == "client" ]]; then
  base="$script_dir/rust/client/src"
  cd "$base"
  packages=($(ls -d -- ../*/ | xargs -n1 | grep "[^../src/]"))
elif [[ "$component" == "server" ]]; then
  base="$script_dir/rust/server/src"
  cd "$base"
  packages=($(ls -d -- ../*/ | xargs -n1 | grep "[^../src/]" | grep "[^../migrations/]" | grep "[^../schema/]"))
  packages+=("..")
fi

for package in "${packages[@]}"; do
  cd "$base" && cd "$package"
  cargo test || exit 1
done

cd "$script_dir"
