DROP TABLE IF EXISTS PolygonPoint;
DROP TABLE IF EXISTS Point;
DROP TABLE IF EXISTS PolygonLabel;
DROP TABLE IF EXISTS Polygon;
DROP TABLE IF EXISTS TilingLabel;
DROP TABLE IF EXISTS Tiling;
DROP TABLE IF EXISTS Label;
