DROP TABLE IF EXISTS PolygonPoint;
DROP SEQUENCE IF EXISTS PolygonPoint;

DROP TABLE IF EXISTS Point;
DROP SEQUENCE IF EXISTS Point;

DROP TABLE IF EXISTS PolygonLabel;
DROP SEQUENCE IF EXISTS PolygonLabel;

DROP TABLE IF EXISTS Polygon;
DROP SEQUENCE IF EXISTS Polygon;

DROP TABLE IF EXISTS TilingLabel;
DROP SEQUENCE IF EXISTS TilingLabel;

DROP TABLE IF EXISTS Tiling;
DROP SEQUENCE IF EXISTS Tiling;

DROP TABLE IF EXISTS Label;
DROP SEQUENCE IF EXISTS Label;
