#!/bin/sh
env="$1"
if [[ "$env" == "" ]] || (($# < 2)); then
  echo Missing environment argument.
  exit 1
fi

set -a
source .env
set +a

ROCKET_ENV="$env" \
DATABASE_URL="postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$TILINGS_DB_SERVICE_HOST:$TILINGS_DB_SERVICE_PORT/$POSTGRES_DB" \
${@:2}
