#!/bin/sh
env="$1"
if [[ "$env" == "" ]] || (($# < 2)); then
  echo Missing environment argument.
  exit 1
fi

set -a
source /dev/stdin <<<"$(credential-1password get --mode="tilings-db-$env" || exit 1)"
set +a

ROCKET_ENV="$env" ${@:2}
