ALTER TABLE Tiling       ADD COLUMN is_locked  BOOLEAN  NOT NULL  DEFAULT FALSE;
ALTER TABLE Polygon      ADD COLUMN is_locked  BOOLEAN  NOT NULL  DEFAULT FALSE;
ALTER TABLE Point        ADD COLUMN is_locked  BOOLEAN  NOT NULL  DEFAULT FALSE;
ALTER TABLE PolygonPoint ADD COLUMN is_locked  BOOLEAN  NOT NULL  DEFAULT FALSE;
ALTER TABLE Atlas        ADD COLUMN is_locked  BOOLEAN  NOT NULL  DEFAULT FALSE;
ALTER TABLE AtlasVertex  ADD COLUMN is_locked  BOOLEAN  NOT NULL  DEFAULT FALSE;
ALTER TABLE AtlasEdge    ADD COLUMN is_locked  BOOLEAN  NOT NULL  DEFAULT FALSE;
