[package]
name = "geometry"
version = "0.2.0"
authors = ["Trey Lowerison <19714082+tlowerison@users.noreply.github.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
float-cmp = "0.8.0"
num-traits = "0.2.14"
