[package]
name = "common"
version = "0.2.7"
authors = ["Trey Lowerison <19714082+tlowerison@users.noreply.github.com>"]
edition = "2018"

[dependencies]
float-cmp = "0.8.0"
itertools = "0.10.0"
num-traits = "0.2.14"
