#!/bin/sh
if [[ "$(which goose)" == "" ]]; then
  go get -u github.com/pressly/goose/cmd/goose
fi

database="$1"
if [[ "$database" == "" ]] || (($# < 2)); then
  echo Missing database argument.
  exit 1
fi

credentials=$(credential-1password get --mode="mysql-$database") || exit 1

goose -dir "$(dirname "$0")/migrations" mysql "$credentials" ${@:2}
