DROP TABLE IF EXISTS AtlasEdge;
DROP SEQUENCE IF EXISTS AtlasEdge;

DROP TABLE IF EXISTS AtlasVertexProtoTile;
DROP SEQUENCE IF EXISTS AtlasVertexProtoTile;

DROP TABLE IF EXISTS AtlasVertex;
DROP SEQUENCE IF EXISTS AtlasVertex;

DROP TABLE IF EXISTS Atlas;
DROP SEQUENCE IF EXISTS Atlas;
