[package]
name = "tile"
version = "0.2.6"
authors = ["Trey Lowerison <19714082+tlowerison@users.noreply.github.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
float-cmp = "0.8.0"
geometry = { path = "../geometry" }
itertools = "0.10.0"
